[tasks.r-update]
description = "Update versions and changelog locally (manual workflow)"
command = "release-plz"
args = ["update"]

[tasks.r-full-pr]
description = "Complete PR workflow: create PR, wait for merge confirmation, then release"
script_runner = "@shell"
script = '''
echo 'Creating release PR...'
TOKEN=$(cat ~/.config/gh/hosts.yml | grep oauth_token | awk '{print $2}')
release-plz release-pr --git-token "$TOKEN"
echo 'Release PR created! Please review and merge it on GitHub.'
echo 'After merging, run: cargo make r-release'
echo 'Or run: cargo make r-release-auto (if you want to release immediately after merge)'
'''

[tasks.r-full]
description = "Complete manual workflow: update, commit, push, and release"
dependencies = ["r-update"]
script_runner = "@shell"
script = '''
git add .
git commit -m 'chore: release'
git push
TOKEN=$(cat ~/.config/gh/hosts.yml | grep oauth_token | awk '{print $2}')
release-plz release --git-token "$TOKEN"
'''